// Happy Hues-Inspired Palettes — Full Color System
// Each palette defines: background, accent (button), border (nav/headline),
// cardBackground, headline, paragraph, buttonText, highlight, secondary, tertiary
//
// The 4 core colors stored in Google Sheets: backgroundColor, accentColor, borderColor, cardBackground
// Extended colors are derived/included for richer UI

export const colorPalettes = [
  {
    id: 1,
    name: "Deep Space",
    description: "Dark & dramatic with vivid purple accents",
    backgroundColor: "#16161a",
    accentColor: "#7f5af0",
    borderColor: "#2cb67d",
    cardBackground: "#242629",
    headline: "#fffffe",
    paragraph: "#94a1b2",
    buttonText: "#fffffe",
    highlight: "#7f5af0",
    secondary: "#72757e",
    tertiary: "#2cb67d",
  },
  {
    id: 2,
    name: "Playful Purple",
    description: "Whimsical with coral & gold highlights",
    backgroundColor: "#f4effc",
    accentColor: "#ff6e6c",
    borderColor: "#1f1235",
    cardBackground: "#ffffff",
    headline: "#1f1235",
    paragraph: "#1b1425",
    buttonText: "#1f1235",
    highlight: "#ff6e6c",
    secondary: "#67568c",
    tertiary: "#fbdd74",
  },
  {
    id: 3,
    name: "Teal & Coral",
    description: "Bold contrast with tropical energy",
    backgroundColor: "#2a9d8f",
    accentColor: "#e76f51",
    borderColor: "#264653",
    cardBackground: "#f1faee",
    headline: "#264653",
    paragraph: "#4a6670",
    buttonText: "#ffffff",
    highlight: "#e9c46a",
    secondary: "#f4a261",
    tertiary: "#e76f51",
  },
  {
    id: 4,
    name: "Fresh Mint",
    description: "Crisp and clean with teal energy",
    backgroundColor: "#d8eefe",
    accentColor: "#3da9fc",
    borderColor: "#094067",
    cardBackground: "#ffffff",
    headline: "#094067",
    paragraph: "#5f6c7b",
    buttonText: "#fffffe",
    highlight: "#3da9fc",
    secondary: "#90b4ce",
    tertiary: "#ef4565",
  },
  {
    id: 5,
    name: "Neo Brutalist",
    description: "High contrast black & electric blue",
    backgroundColor: "#0f0e17",
    accentColor: "#ff8906",
    borderColor: "#f25f4c",
    cardBackground: "#232136",
    headline: "#fffffe",
    paragraph: "#a7a9be",
    buttonText: "#fffffe",
    highlight: "#ff8906",
    secondary: "#e53170",
    tertiary: "#f25f4c",
  },
  {
    id: 6,
    name: "Royal Burgundy",
    description: "Rich, premium feel with gold accents",
    backgroundColor: "#6b2737",
    accentColor: "#d4a853",
    borderColor: "#2d1117",
    cardBackground: "#fdf6ec",
    headline: "#2d1117",
    paragraph: "#5c4444",
    buttonText: "#ffffff",
    highlight: "#d4a853",
    secondary: "#8b4557",
    tertiary: "#c49b6b",
  },
  {
    id: 7,
    name: "Midnight Garden",
    description: "Lush dark greens with gold accents",
    backgroundColor: "#1a1a2e",
    accentColor: "#e2b714",
    borderColor: "#16213e",
    cardBackground: "#0f3460",
    headline: "#edf2f4",
    paragraph: "#8d99ae",
    buttonText: "#1a1a2e",
    highlight: "#e2b714",
    secondary: "#533483",
    tertiary: "#e94560",
  },
  {
    id: 8,
    name: "Ocean Breeze",
    description: "Cool blues with warm coral pop",
    backgroundColor: "#004643",
    accentColor: "#f9bc60",
    borderColor: "#abd1c6",
    cardBackground: "#001e1d",
    headline: "#fffffe",
    paragraph: "#abd1c6",
    buttonText: "#001e1d",
    highlight: "#f9bc60",
    secondary: "#e8e4e6",
    tertiary: "#abd1c6",
  },
  {
    id: 9,
    name: "Candy Pop",
    description: "Bright & playful pink with blue contrast",
    backgroundColor: "#f72585",
    accentColor: "#4cc9f0",
    borderColor: "#3a0ca3",
    cardBackground: "#ffffff",
    headline: "#3a0ca3",
    paragraph: "#4a4e69",
    buttonText: "#ffffff",
    highlight: "#4cc9f0",
    secondary: "#7209b7",
    tertiary: "#4361ee",
  },
  {
    id: 10,
    name: "Forest Calm",
    description: "Earthy greens with natural warmth",
    backgroundColor: "#2d6a4f",
    accentColor: "#d8f3dc",
    borderColor: "#1b4332",
    cardBackground: "#f1faee",
    headline: "#1b4332",
    paragraph: "#40916c",
    buttonText: "#1b4332",
    highlight: "#95d5b2",
    secondary: "#52b788",
    tertiary: "#b7e4c7",
  },
  {
    id: 11,
    name: "Warm Terracotta",
    description: "Mediterranean warmth, refined & grounded",
    backgroundColor: "#e07a5f",
    accentColor: "#f2cc8f",
    borderColor: "#3d405b",
    cardBackground: "#f4f1de",
    headline: "#3d405b",
    paragraph: "#5c5e6e",
    buttonText: "#3d405b",
    highlight: "#f2cc8f",
    secondary: "#81b29a",
    tertiary: "#e07a5f",
  },
  {
    id: 12,
    name: "Arctic Ice",
    description: "Icy blues with electric accents",
    backgroundColor: "#e8f1f2",
    accentColor: "#0077b6",
    borderColor: "#023e8a",
    cardBackground: "#ffffff",
    headline: "#023e8a",
    paragraph: "#4a5568",
    buttonText: "#ffffff",
    highlight: "#00b4d8",
    secondary: "#48cae4",
    tertiary: "#90e0ef",
  },
  {
    id: 13,
    name: "Noir Luxe",
    description: "Sophisticated black with gold elegance",
    backgroundColor: "#14213d",
    accentColor: "#fca311",
    borderColor: "#000000",
    cardBackground: "#1d2d50",
    headline: "#e5e5e5",
    paragraph: "#a0a0a0",
    buttonText: "#000000",
    highlight: "#fca311",
    secondary: "#e5e5e5",
    tertiary: "#ffd166",
  },
  {
    id: 14,
    name: "Lavender Dream",
    description: "Soft purple with peachy warmth",
    backgroundColor: "#e2d5f1",
    accentColor: "#ff6b6b",
    borderColor: "#4a2c6e",
    cardBackground: "#ffffff",
    headline: "#4a2c6e",
    paragraph: "#6b5b7b",
    buttonText: "#ffffff",
    highlight: "#ff6b6b",
    secondary: "#a78bba",
    tertiary: "#ffd97d",
  },
  {
    id: 15,
    name: "Citrus Burst",
    description: "Vibrant orange & yellow energy",
    backgroundColor: "#ff6d00",
    accentColor: "#ffea00",
    borderColor: "#3d0000",
    cardBackground: "#fffbf0",
    headline: "#3d0000",
    paragraph: "#5c4033",
    buttonText: "#3d0000",
    highlight: "#ffea00",
    secondary: "#ff9100",
    tertiary: "#ffab40",
  },
  {
    id: 16,
    name: "Sage & Clay",
    description: "Organic, natural, and grounding",
    backgroundColor: "#e8e0d0",
    accentColor: "#6b7f5e",
    borderColor: "#3c3836",
    cardBackground: "#ffffff",
    headline: "#3c3836",
    paragraph: "#665c54",
    buttonText: "#ffffff",
    highlight: "#6b7f5e",
    secondary: "#9a8c6c",
    tertiary: "#c4a882",
  },
  {
    id: 17,
    name: "Electric Night",
    description: "Cyberpunk neon on dark canvas",
    backgroundColor: "#0d0221",
    accentColor: "#0abdc6",
    borderColor: "#ea00d9",
    cardBackground: "#150734",
    headline: "#0abdc6",
    paragraph: "#7a7d8e",
    buttonText: "#0d0221",
    highlight: "#ea00d9",
    secondary: "#711c91",
    tertiary: "#133e7c",
  },
];
