// All 17 Happy Hues Palettes
// Mapped to our loyalty system colors

export const colorPalettes = [
  {
    id: 1,
    name: "Calm & Serene",
    description: "Professional and trustworthy",
    backgroundColor: "#2d4059",
    accentColor: "#ea5455",
    borderColor: "#ea5455",
    cardBackground: "#f8f8f8",
  },
  {
    id: 2,
    name: "Warm & Inviting",
    description: "Friendly and approachable",
    backgroundColor: "#f07167",
    accentColor: "#0081a7",
    borderColor: "#0081a7",
    cardBackground: "#fdfcdc",
  },
  {
    id: 3,
    name: "Fresh & Modern",
    description: "Clean and contemporary",
    backgroundColor: "#07beb8",
    accentColor: "#3dccc7",
    borderColor: "#68d8d6",
    cardBackground: "#f4f4f4",
  },
  {
    id: 4,
    name: "Bold & Vibrant",
    description: "Eye-catching and energetic",
    backgroundColor: "#f72585",
    accentColor: "#7209b7",
    borderColor: "#3a0ca3",
    cardBackground: "#f8f9fa",
  },
  {
    id: 5,
    name: "Earth Tones",
    description: "Natural and grounded",
    backgroundColor: "#bc6c25",
    accentColor: "#dda15e",
    borderColor: "#606c38",
    cardBackground: "#fefae0",
  },
  {
    id: 6,
    name: "Ocean Blues",
    description: "Calm and reliable",
    backgroundColor: "#0077b6",
    accentColor: "#00b4d8",
    borderColor: "#023e8a",
    cardBackground: "#caf0f8",
  },
  {
    id: 7,
    name: "Sunset Glow",
    description: "Warm and welcoming",
    backgroundColor: "#ff6b6b",
    accentColor: "#ffd93d",
    borderColor: "#6c5ce7",
    cardBackground: "#fff5e4",
  },
  {
    id: 8,
    name: "Forest Green",
    description: "Fresh and organic",
    backgroundColor: "#52b788",
    accentColor: "#95d5b2",
    borderColor: "#2d6a4f",
    cardBackground: "#f1faee",
  },
  {
    id: 9,
    name: "Purple Passion",
    description: "Creative and luxurious",
    backgroundColor: "#7209b7",
    accentColor: "#f72585",
    borderColor: "#3a0ca3",
    cardBackground: "#f8f9fa",
  },
  {
    id: 10,
    name: "Coral & Teal",
    description: "Playful and modern",
    backgroundColor: "#ff6f61",
    accentColor: "#48a9a6",
    borderColor: "#2a9d8f",
    cardBackground: "#fef9ef",
  },
  {
    id: 11,
    name: "Midnight Blue",
    description: "Sophisticated and elegant",
    backgroundColor: "#14213d",
    accentColor: "#fca311",
    borderColor: "#e5e5e5",
    cardBackground: "#f8f9fa",
  },
  {
    id: 12,
    name: "Peach & Navy",
    description: "Balanced and refined",
    backgroundColor: "#264653",
    accentColor: "#e76f51",
    borderColor: "#2a9d8f",
    cardBackground: "#f4f1de",
  },
  {
    id: 13,
    name: "Mint Fresh",
    description: "Light and airy",
    backgroundColor: "#06ffa5",
    accentColor: "#00d9ff",
    borderColor: "#7209b7",
    cardBackground: "#ffffff",
  },
  {
    id: 14,
    name: "Retro Vibes",
    description: "Fun and nostalgic",
    backgroundColor: "#f4442e",
    accentColor: "#f9c80e",
    borderColor: "#662e9b",
    cardBackground: "#f8f7ff",
  },
  {
    id: 15,
    name: "Professional Gray",
    description: "Corporate and clean",
    backgroundColor: "#495057",
    accentColor: "#0077b6",
    borderColor: "#343a40",
    cardBackground: "#f8f9fa",
  },
  {
    id: 16,
    name: "Lavender Dreams",
    description: "Soft and calming",
    backgroundColor: "#b8a8cc",
    accentColor: "#ffcce1",
    borderColor: "#9381ad",
    cardBackground: "#fff8f0",
  },
  {
    id: 17,
    name: "Citrus Pop",
    description: "Bright and cheerful",
    backgroundColor: "#ffba08",
    accentColor: "#e85d04",
    borderColor: "#d00000",
    cardBackground: "#fffcf2",
  },
];
